### ISSUE TITLE
Data from teamgames

### ISSUE THREAD

**Issue by duilio92** [jerkeeler/aoestats-frontend#1]
Hi have you considered adding support for team-games data? Are you considering taking help? I would like to contribute trying to code that, if it is ok with you.

**Comment by jerkeeler** [comment]
Hi @duilio92 I am planning on adding support for the team game ladder. Some of my stat calculations will have to be adjusted in order to support it.

I would consider taking help, but at this time it'd be tough to develop since my backend code IS in a private repository, along with the db schemas. I am working on cleaning up that code and open sourcing it in the future.

**Comment by duilio92** [comment]
Ok, no problem, thanks for your response!
