### ISSUE TITLE
Custom elo range

### ISSUE THREAD

**Issue by RediRodion** [jerkeeler/aoestats-frontend#4]
Since the amount of games played on the highest level (1650+) is already so small and there are balance changes implemented every month (changing civilizations, their strength and therefore pickrate and winrate)
it would be advisable if the user had more freedom with elo range selection
By doing that the sample size would be increased yet still would provide information from games on the highest possible level.

It would make sense to be able to choose elo ranges of hundreds (1000, 1100, 1200, ...) or allow users to select custom elo numbers for the database (minimum and maximum elo range).

![2020-05-26 19_33_45-Window](https://user-images.githubusercontent.com/65970317/82931889-e33c4280-9f87-11ea-8c60-db38627c840e.png)

Best Regards,
RediRodion

**Comment by jerkeeler** [comment]
I love this idea. I don't think it's feasible in the current iteration of the site. Namely I have it set up to generate all content statically, daily. There is no API being hit when someone selects an Elo range. Each Elo range is its own page. 

Aside from technical limitations in its current form, I believe custom brackets might be fairly expensive, computationally. Having to load all the data into memory, bucket by Elo, bucket by game duration, map, etc.. I think the web request could take a while and would be blocking.

I'm going to close this for now since it's _currently_ not feasible. I would love to revisit this in a few months to see if that has changed. Because, I agree, this would be a killer feature to have.

P.S. I'm working on an API to grab the match data. So, you could get the data and do your own analysis if interested.

**Comment by RediRodion** [comment]
hi jerkeeler, thank you for your answer.

Since we hit a new patch a small change would be good to make in this very moment.
If all content is stored statically then as a temporary solution could you increase an elo range for the highest level? Instead of making it 1650+ make it perhaps 1550+?

Best Regards and thanks!

**Comment by jerkeeler** [comment]
Hmmm. I need to look at the ratings distribution again. I agree, probably need to make that upper bracket wider. When I make that bracket wider, I'll eat up some from the lower brackets. Overall, I think I just need to adjust the brackets as whole. Stay tuned.

**Comment by RediRodion** [comment]
Cool! Thanks!
